# Generated by Django 4.2.11 on 2024-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('EmailID', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Phone', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('Place', models.CharField(max_length=30)),
            ],
        ),
    ]
