# Generated by Django 4.2.11 on 2024-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0002_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Item', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=30)),
                ('Contact_no', models.CharField(max_length=30)),
                ('Pic', models.ImageField(upload_to='static/images/donation/clothes/')),
            ],
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Item', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=30)),
                ('Contact_no', models.CharField(max_length=30)),
                ('Pic', models.ImageField(upload_to='static/images/donation/foods/')),
            ],
        ),
    ]
