# Generated by Django 4.2.11 on 2024-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0003_clothes_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('ItemType', models.CharField(max_length=30)),
                ('ItemName', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('PhoneNumber', models.BigIntegerField()),
            ],
        ),
    ]
