# Generated by Django 5.0 on 2024-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0004_requestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('PlaceAllocation', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('on the way', 'On the way')], default='pending', max_length=30)),
            ],
        ),
    ]
