# Generated by Django 5.0 on 2024-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0005_driverlogindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('on the way', 'On the way')], default='pending', max_length=30),
        ),
    ]
